name: FE Code Style Checker

on:
  workflow_dispatch:

jobs:
  java-checkstyle:
    name: "CheckStyle"
    runs-on: ${{ matrix.os }}
    if: |-
      always()
    steps:
      - name: Enable long paths (Windows)
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true
        continue-on-error: true

      - name: Disable autocrlf (Windows)
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - name: Paths Filter
        uses: ./.github/actions/paths-filter
        id: filter
        with:
          filters: |
            fe_changes:
              - 'fe/**'
              - 'gensrc/proto/**'
              - 'gensrc/thrift/**'

      - name: Set up JDK with Maven
        if: always()
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run java checkstyle
        if: always()
        run: cd fe && mvn clean checkstyle:check

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
